### ISSUE TITLE
the project is perfect, but I can't run it succcessful

### ISSUE THREAD

**Issue by titan-web** [Yelp/data_pipeline#10]
I hope you can clearly describe the installation process of the whole project. very very very thanks

**Comment by lsterk** [comment]
Hi! This repository is intended to be a demonstration of the concepts in our [tech blog series](https://engineeringblog.yelp.com/2016/07/billions-of-messages-a-day-yelps-real-time-data-pipeline.html). We don't expect this to work out of the box, and can't provide support beyond the README file and the code docs.

Thanks for checking out this repo! 😄
