### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by laucia** [Yelp/data_pipeline#11]
Contrary to what the setup.py states, the code is not python 3 compatible.

**Comment by lsterk** [comment]
Hi! This repository is intended to be a demonstration of the concepts in our [tech blog series](https://engineeringblog.yelp.com/2016/07/billions-of-messages-a-day-yelps-real-time-data-pipeline.html). We don't expect this to work out of the box, and can't provide support beyond the README file and the code docs.

Thanks for checking out this repo! 😄
